### ISSUE TITLE
maxBuffer exceeded

### ISSUE THREAD

**Issue by irega** [zpbappi/gulp-chutzpah#6]
@zpbappi We have another error now:

> [09:45:25] Error: stdout maxBuffer exceeded
> at Socket.onChildStdout (child_process.js:328:14)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at addChunk (_stream_readable.js:263:12)
> at readableAddChunk (_stream_readable.js:246:13)
> at Socket.Readable.push (_stream_readable.js:208:10)
> at Pipe.onread (net.js:594:20)

You can solve it with this exec command option:

> var executeOptions = {
> maxBuffer: 10000 * 1024
> };
> exec(command, executeOptions, function (err, stdout, stderr) {
> console.log(stdout);
> console.error(stderr);
> callback(err);
> });

I think that the "10000" value must be configurable through the plugin options (200 by default), what do you think? If its ok, I will send a new pull request.

**Comment by zpbappi** [comment]
@irega sorry, I was away for a while. it is a nice addition. I will continue further communication in the PR.

**Comment by zpbappi** [comment]
@irega pull request is merged, updated npm package is released. Thank you for your contribution.
